create table if not exists public.bus_routes_cache (
  id bigint generated by default as identity primary key,
  route_key text not null unique,
  brt_id text,
  brt_stdid text,
  brt_class text,
  brt_no text,
  start_name text,
  end_name text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists bus_routes_cache_brt_id_idx on public.bus_routes_cache(brt_id);
create index if not exists bus_routes_cache_brt_stdid_idx on public.bus_routes_cache(brt_stdid);

create table if not exists public.bus_route_stops_cache (
  id bigint generated by default as identity primary key,
  route_id text not null,
  stop_key text not null,
  sequence_no integer,
  node_id text,
  node_name text,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(route_id, stop_key)
);

create index if not exists bus_route_stops_cache_route_idx on public.bus_route_stops_cache(route_id);
create index if not exists bus_route_stops_cache_node_idx on public.bus_route_stops_cache(node_id);

alter table public.bus_routes_cache enable row level security;
alter table public.bus_route_stops_cache enable row level security;

drop policy if exists "public can read bus route cache" on public.bus_routes_cache;
create policy "public can read bus route cache"
on public.bus_routes_cache for select
using (true);

drop policy if exists "public can read bus route stops cache" on public.bus_route_stops_cache;
create policy "public can read bus route stops cache"
on public.bus_route_stops_cache for select
using (true);
